Fix warnings and errors on Windows/MSVC (#24)
- Implement strlcat (as __bdd_strlcat__) instead of using BSD function
  (nonstandard, not available on Win32)
- Address alloc function warnings by checking for NULL returns
  (print error message and abort on failure)
- Fix error C2036 by casting void* to char* before increment
  (void* operations rely on nonstandard GCC extension)